include:
  - path:
    - docker/services/fonts.yml
    - docker/services/umami.yml
    - docker/services/certbot.yml
    project_directory: .

services:
  nuxt:
    container_name: wokalek-nuxt
    build:
      dockerfile: docker/nuxt/prod.Dockerfile
      args:
        - NODE_VERSION=${NUXT_NODE_VERSION}
    restart: always
    env_file: env/nuxt/.env
    depends_on:
      fonts:
        condition: service_completed_successfully
    volumes:
      - nuxt-node_modules:/nuxt/node_modules
      - ./nuxt/src:/nuxt/src

  nginx:
    container_name: wokalek-nginx
    image: wokalek/nginx-brotli:${NGINX_VERSION}
    restart: always
    depends_on:
      - nuxt
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/prod.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - ./static:/usr/share/nginx/html/static
      - ./volumes/nginx/cache:/data/nginx/cache
      - ./volumes/nginx/log:/var/log/nginx
      - ./volumes/certbot/www:/certbot/www
      - ./volumes/certbot/conf/live/wokalek.ru/fullchain.pem:/certbot/certs/fullchain.pem
      - ./volumes/certbot/conf/live/wokalek.ru/privkey.pem:/certbot/certs/privkey.pem

volumes:
  nuxt-node_modules:
