include:
  - path:
    - docker/services/fonts.yml
    project_directory: .

services:
  nuxt:
    container_name: wokalek-nuxt
    build:
      dockerfile: docker/nuxt/prod.Dockerfile
      args:
        - NODE_VERSION=${NUXT_NODE_VERSION}
    env_file: env/nuxt/.env
    depends_on:
      fonts:
        condition: service_completed_successfully
    volumes:
      - nuxt-node_modules:/nuxt/node_modules
      - ./nuxt/src:/nuxt/src

  nginx:
    container_name: wokalek-nginx
    user: root
    image: wokalek/nginx-brotli:${NGINX_VERSION}
    depends_on:
      - nuxt
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/dev.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - ./static:/usr/share/nginx/html/static
      - ./volumes/nginx/cache:/data/nginx/cache
      - ./volumes/nginx/log:/var/log/nginx

volumes:
  nuxt-node_modules:
