version: "3.8"

services:
  nuxt:
    container_name: wokalek-nuxt
    build:
      context: .
      dockerfile: docker/nuxt.dev.Dockerfile
    env_file: env/nuxt/.env
    depends_on:
      fonts:
        condition: service_completed_successfully
    ports:
      - 24678:24678 #Для работы HMR
    volumes:
      - nuxt-devfolder:/nuxt/.nuxt
      - ./nuxt/nuxt.config.ts:/nuxt/nuxt.config.ts
      - ./nuxt/tsconfig.json:/nuxt/tsconfig.json
      - ./nuxt/src:/nuxt/src
      - ./static:/nuxt/src/public/static

  nginx:
    container_name: wokalek-nginx
    image: fholzer/nginx-brotli
    depends_on:
      - nuxt
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./nginx/types/gzip_types.conf:/etc/nginx/gzip_types.conf
      - ./nginx/types/brotli_types.conf:/etc/nginx/brotli_types.conf
      - ./static:/usr/share/nginx/html/static

  fonts:
    container_name: wokalek-fonts
    build: https://github.com/wokalek/glyphhanger.git
    entrypoint: ["bash", "/build.sh"]
    volumes:
      - ./fonts/build.sh:/build.sh
      - ./nuxt/src/assets/fonts:/app

volumes:
  nuxt-devfolder:
