include:
  - path:
    - docker/services/fonts.yml
    project_directory: .

services:
  nginx:
    container_name: wokalek-nginx
    image: wokalek/nginx-brotli:${NGINX_VERSION:?error}
    depends_on:
      - nuxt
      - django
    ports:
      - 80:80
      - 8000:8000
    volumes:
      - ./nginx/conf/dev.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - django-static:/django/static
      - ./django/media:/django/media

  nuxt:
    container_name: wokalek-nuxt
    build:
      dockerfile: docker/nuxt/dev.Dockerfile
      args:
        - NODE_VERSION=${NUXT_NODE_VERSION:?error}
    env_file: env/nuxt/.env
    depends_on:
      fonts:
        condition: service_completed_successfully
    volumes:
      - nuxt-node_modules:/nuxt/node_modules
      - ./nuxt/src:/nuxt/src
      - ./nuxt/nuxt.config.ts:/nuxt/nuxt.config.ts
      - ./django/media:/nuxt/src/public/media

  django:
    container_name: wokalek-django
    build:
      dockerfile: docker/django/dev.Dockerfile
      args:
        - PYTHON_VERSION=${DJANGO_PYTHON_VERSION:?error}
    env_file: env/django/.env
    volumes:
      - django-static:/static
      - ./django:/django

volumes:
  nuxt-node_modules:
  django-static:
