include:
  - path:
    - docker/services/fonts.yml
    project_directory: .

services:
  nginx:
    container_name: wokalek-nginx
    user: root
    image: wokalek/nginx-brotli:${NGINX_VERSION:?error}
    depends_on:
      - nuxt
      - django
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/dev.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - ./static:/usr/share/nginx/html/static

  nuxt:
    container_name: wokalek-nuxt
    build:
      dockerfile: docker/nuxt/dev.Dockerfile
      args:
        - NODE_VERSION=${NUXT_NODE_VERSION:?error}
    env_file: env/nuxt/.env
    depends_on:
      fonts:
        condition: service_completed_successfully
    volumes:
      - nuxt-node_modules:/nuxt/node_modules
      - ./nuxt/src:/nuxt/src
      - ./nuxt/nuxt.config.ts:/nuxt/nuxt.config.ts

  django:
    container_name: wokalek-django
    build:
      dockerfile: docker/django/dev.Dockerfile
      args:
        - PYTHON_VERSION=${DJANGO_PYTHON_VERSION:?error}
    env_file: env/django/.env
    ports:
      - 8000:8000
    volumes:
      - ./django:/django

volumes:
  nuxt-node_modules:
