[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "v3.12.4"
django = "^5.0.6"
django-mdeditor = "^0.1.20"
pillow = "^10.4.0"
django-imagefield = "^0.18.0"
django-cleanup = "^8.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poe.tasks]
makemigrations = "python manage.py makemigrations"
migrate = "python manage.py migrate"
runserver = "python manage.py runserver"
dev.sequence = ["makemigrations", "migrate", "runserver"]
check = "python manage.py check"
