services:
  umami:
    container_name: wokalek-umami
    image: ghcr.io/umami-software/umami:postgresql-v${UMAMI_VERSION}
    restart: always
    env_file: env/umami/.env
    depends_on:
      umami-db:
        condition: service_healthy

  umami-db:
    container_name: wokalek-umami-db
    image: postgres:${UMAMI_DB_VERSION}-alpine
    restart: always
    env_file: env/umami-db/.env
    ports:
      - 5432:5432
    volumes:
      - ./volumes/umami-db/data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
