services:
  umami:
    container_name: wokalek-umami
    image: ghcr.io/umami-software/umami:postgresql-v${UMAMI_VERSION:?error}
    restart: always
    env_file: env/umami/.env
    depends_on:
      umami-db:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl http://localhost:3000/api/heartbeat']
      interval: 5s
      timeout: 5s
      retries: 5

  umami-db:
    container_name: wokalek-umami-db
    image: postgres:${UMAMI_POSTGRES_VERSION}-alpine
    restart: always
    env_file: env/umami-db/.env
    ports:
      - 5432:5432
    volumes:
      - ./volumes/umami-db/data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 5s
      timeout: 5s
      retries: 5
