name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Run ssh action with git pull and docker rebuild
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }}
        username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
        password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
        script: |
          cd ${{ secrets.DEPLOY_SERVER_WORK_DIR }}
          git pull
          docker compose -f docker-compose.prod.yml up -d --build
